#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# Description: Build Kernel using GitHub Actions
# Change from P3TERX
# Based on: https://github.com/ylx2016/kernel/blob/master/.github/workflows/Debian_kernel_latest.yml
#

name: Make Venus Kernel

on:
  workflow_dispatch:

env:
  UPLOAD_DIR: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/qctt/kernelbuild:debian12
    
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        submodules: 'recursive'
        fetch-depth: 0
    
    - name: Prepare Clang
      id: clang
      working-directory: /workdir
      run: |
        git clone --recursive --depth 1 https://gitlab.com/jjpprrrr/prelude-clang.git clang
        export PATH=/workdir/clang/bin:$PATH
        echo -e "Path: $PATH"
        echo $PATH >> $GITHUB_PATH
    
    - name: Get source code
      id: code
      working-directory: /workdir
      if: (!cancelled()) && success()
      run: |
        git clone --recursive --depth 1 https://github.com/wwlwwlwwlwwl/kernel_xiaomi_venus.git kernel
        
    - name: Compile the kernel
      id: compile
      if: (!cancelled()) && success()
      working-directory: /workdir
      run: |
        df -hT $PWD
        export CLANG_CMDLINE="-j$(nproc) O=out ARCH=arm64 CC=/workdir/clang/bin/clang CXX=/workdir/clang/bin/clang++ CROSS_COMPILE_ARM32=/workdir/clang/bin/arm-linux-gnueabi- CLANG_TRIPLE=/workdir/clang/bin/aarch64-linux-gnu- CROSS_COMPILE=/workdir/clang/bin/aarch64-linux-gnu- LD=/workdir/clang/bin/ld.lld"
        cd kernel
        echo "Configure kernel config"
        sudo time make $CLANG_CMDLINE vendor/venus-qgki_defconfig
        echo -e "Start compile with cmdline: $CLANG_CMDLINE"
        sudo time make $CLANG_CMDLINE
        mv out/arch/arm64/boot/Image /workdir/upload
        echo '::set-output name=action_echo::enabled'
        echo "::set-output name=compile::success"
    
    - name: Check space usage
      if: (!cancelled()) && success()
      run: df -hT
    
    - name: Upload
      uses: actions/upload-artifact@main
      if: (!cancelled()) && success() && env.UPLOAD_DIR == 'true'
      with:
        name: Image
        path: /workdir/upload
    
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 10
